// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function stripQuotes(v: unknown) {
  if (v == null) return '';
  const s = String(v).trim();
  return s.replace(/^\"|\"$/g, '');
}

const SUPABASE_URL = stripQuotes(import.meta.env.VITE_SUPABASE_URL);
const SUPABASE_PUBLISHABLE_KEY = stripQuotes(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Helpful runtime message for developers when env vars are missing or incorrect
  // The frontend needs VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (anon/public key).
  // Check your project root .env and make sure values are the Project URL and the anon (public) key.
  // Example (no surrounding quotes):
  // VITE_SUPABASE_URL=https://your-project.supabase.co
  // VITE_SUPABASE_PUBLISHABLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
  // If you see "Invalid API key" on login, this is the first thing to verify.
  // Do not commit real keys to source control.
  // eslint-disable-next-line no-console
  console.error('Supabase client missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Check your .env');
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});